# Generated by Django 4.1 on 2022-09-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0026_alter_orders_customer_alter_orders_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ossapp.product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ossapp.customer'),
        ),
    ]
