# Generated by Django 4.1 on 2022-09-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0027_alter_shoppingcart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
