# Generated by Django 4.1 on 2022-09-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0028_alter_shoppingcart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='Product',
            new_name='product',
        ),
    ]
