# Generated by Django 4.1 on 2022-10-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0029_rename_product_shoppingcart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
