# Generated by Django 4.1 on 2022-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0030_delete_login_delete_orders_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.IntegerField()),
                ('checkout', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('person', models.IntegerField()),
                ('contactno', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('emailaddress', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('selectcity', models.CharField(max_length=10)),
                ('selectstate', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
