# Generated by Django 4.1 on 2022-11-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0031_customer2_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer2',
            old_name='emailaddress',
            new_name='email',
        ),
    ]
