# Generated by Django 4.1 on 2022-11-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0032_rename_emailaddress_customer2_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer2',
            old_name='checkin',
            new_name='checkIn',
        ),
    ]
