# Generated by Django 4.1 on 2022-11-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0033_rename_checkin_customer2_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer2',
            old_name='contactno',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='customer2',
            old_name='phone',
            new_name='phone2',
        ),
    ]
