# Generated by Django 4.1 on 2022-11-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0034_rename_contactno_customer2_phone1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer2',
            new_name='Customer',
        ),
    ]
