# Generated by Django 4.1 on 2022-11-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0035_rename_customer2_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='checkIn',
            new_name='checkin',
        ),
    ]
