# Generated by Django 4.1 on 2022-11-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0037_alter_customer_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkout',
            field=models.IntegerField(max_length=10),
        ),
    ]
