# Generated by Django 4.1 on 2022-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0038_alter_customer_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.IntegerField(max_length=10),
        ),
    ]
