# Generated by Django 4.1 on 2022-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0039_alter_customer_age_alter_customer_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkin',
            field=models.DateField(),
        ),
    ]
