# Generated by Django 4.1 on 2022-11-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0042_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.IntegerField(),
        ),
    ]
